### ISSUE TITLE
using flock in tmp dir may yields unexpected results

### ISSUE THREAD

**Issue by ohadlevy** [PagerDuty/blender#20]
Hi,

while trying it out, I just create a simple /tmp/exampe.rb and executed:
```USER=root blend -f /tmp/example.rb```

and got the following trace:
``` 
3 job(s) computed using 'Default' strategy
Run failed (0.000161113 s)

blender/lib/blender/lock/flock.rb:48:in `release': undefined method `flock' for nil:NilClass (NoMethodError)
from blender/lib/blender/lock/flock.rb:60:in `ensure in with_lock'
from blender/lib/blender/lock/flock.rb:60:in `with_lock'
from blender/lib/blender/scheduler/dsl.rb:150:in `lock'
from blender/lib/blender/scheduler.rb:58:in `run'
from blender/lib/blender.rb:44:in `blend'
from blender/lib/blender/cli.rb:54:in `from_file'
```

moving the file elsewhere solved the issue.

**Comment by ranjib** [comment]
locks are disabled by default now, user have to opt in specifically for this, in which case, they'll be controlling the path
